obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  oppo_project/
obj-$(CONFIG_OPPO_DEVICE_IFNO)	+=  oppo_devinfo/
obj-$(CONFIG_OPPO_DEBUG_ASSERT)	+=  oppo_trace/
obj-$(CONFIG_RECORD_MDMRST)     +=  oppo_mdmrst/
#ifdef CONFIG_PRODUCT_REALME_RMX1801
#//John.Xu@PhoneSw.AudioDriver, 2016/02/22, Add for critical_log
obj-y     +=  oppo_criticallog/
#endif /* CONFIG_PRODUCT_REALME_RMX1801 */

#//wenbin.liu@PSW.Kernel.MM, 2018/05/23, Add for Healthinfo monitor
obj-y     +=  oppo_healthinfo/
#endif /* CONFIG_PRODUCT_REALME_RMX1801 */

#ifdef CONFIG_PRODUCT_REALME_RMX1801
#wen.luo@PSW.Kernel.MM, 2018/05/23, Add for Healthinfo monitor
obj-$(CONFIG_OPPO_SHUTDOWN_DETECT)	+=  oppo_shutdown_detect/
#endif /* CONFIG_PRODUCT_REALME_RMX1801 */

#GaoTing.Gan@PSW.MultiMedia.MediaServer, 2019/03/07, Add for kevent feedback
obj-y     +=  oppo_kevent_feedback/
#endif /* CONFIG_PRODUCT_REALME_RMX1801 */
